### ISSUE TITLE
TypeError: Cannot read property '_handleConnect' of undefined

### ISSUE THREAD

**Issue by tab00** [lamhieu-vk/meteorx#8]
I got this error after upgrading my app to use Meteor 2.6:

> TypeError: Cannot read property '_handleConnect' of undefined
>     at exposeLivedata (packages\lamhieu_meteorx.js:26:25)
>     at packages\lamhieu_meteorx.js:200:1
>     at packages\lamhieu_meteorx.js:225:4
>     at packages\lamhieu_meteorx.js:233:3

Please update the code to make it compatible with the latest release of Meteor. Thank you.

**Comment by RahulKumarTechahead** [comment]
montiapm:meteorx is a maintained fork: https://packosphere.com/montiapm/meteorx
You can see what packages depend on lamhieu:meteorx by running meteor list --tree
